### ISSUE TITLE
Setting up new store error with mySQL: prisma.session.upsert() invocation

### ISSUE THREAD

**Issue by alexandrosk** [kinngh/shopify-nextjs-prisma-app#14]
When trying to setup a new store I found this issue 

The provided value for the column is too long for the column's type. Column: desc 

If anyone finds this issue 
is easily resolved by adding `@db.Text` after String on Prisma strings so it will be more than 191 characters

**Comment by kinngh** [comment]
If you're on MySQL, that's required but PostgreSQL doesn't need it I believe since that's what I tested it on. Are you trying this with MySQL?

**Comment by alexandrosk** [comment]
Yes indeed, I believe we can close it then just in case someone searches this :)

**Comment by kinngh** [comment]
I've added a note [12393e3770bc972937d6756bbf188b05aa80e38b](https://github.com/kinngh/shopify-nextjs-prisma-app/commit/12393e3770bc972937d6756bbf188b05aa80e38b) in `schema.prisma` for this. Thank you for flagging!
