### ISSUE TITLE
Allow Empty Scopes

### ISSUE THREAD

**Issue by dcrgll** [kinngh/shopify-nextjs-prisma-app#18]
Great project @kinngh, thanks for your hard work on this.

I've come across an issue with project setup where I cannot have an empty `scopes` in `shopify.js`.

I've tried undefined, null, [], [''], [' '] but all seem to return the same OAuth error invalid_scope error.

Have you found a way around this? my app is being rejected for using scopes not in use in the app, but setting no scopes does not appear to be an option.

**Comment by kinngh** [comment]
Hey! So any app that doesn't use any scopes is rather....odd. If you're not reading/writing data around customers, orders, products or content, what is the app doing in the first place? Even going by Shopify's official api docs, the scopes are `required` [ref](https://github.com/Shopify/shopify-api-js/blob/main/docs/reference/shopifyApi.md)

Out of curiosity, I wanna know what you're building that doesn't require a single scope. Please know that it's coming from a good place and I'm genuinely curious!

PS: Thank you so much for the kind words!

**Comment by dcrgll** [comment]
It's a simple feedback app, but in our v1 we're not linking the feedback to any customers or products just yet.

**Comment by kinngh** [comment]
You're better off adding some sort of connection because this is something even I don't have control over since it comes from Shopify's API lib. Or you can ask for at least one permission scope and add some sort of indicator that you're using it and resubmit, which should work out. Sadly, I can't recommend anything else^
