### ISSUE TITLE
Could not find OAuth cookie

### ISSUE THREAD

**Issue by ifat802** [kinngh/shopify-nextjs-prisma-app#25]
I have created a private app for one of my merchants. It was working fine but after some days the app doesn't work with this error message 
![Screenshot at Jun 22 11-44-28](https://github.com/kinngh/shopify-nextjs-prisma-app/assets/127825723/ba99c3f6-5169-4969-84d5-56088d56908e)

I have to reinstall the app to get it working again.

I have checked your code it should automatically go through the whole auth process again. 

![Screenshot at Jun 22 11-49-07](https://github.com/kinngh/shopify-nextjs-prisma-app/assets/127825723/d9dfee6c-a4ff-408b-a3d8-99a51e3ee3a7)

I have checked the database it deleted the session but It doesn't redirect the whole auth process again. 

Any idea why this issue occurring?

**Comment by kinngh** [comment]
I've been recently getting reports about this -  a quick fix is to manually run the auth again by the URL after uninstalling the app. Weirdly enough, having pushed out ~50+ apps at this point, I've never seen this issue at any point so there has to be a piece of documentation I'm either missing or something's actually going wrong. Is there a way to reliably replicate this error?

**Comment by ifat802** [comment]
I have tried to recreate the issue but couldn't able to do it.
if I can I will let you know. 
Thanks.

**Comment by kinngh** [comment]
Is this happening in dev mode or in production? Also, try removing `node_modules` and `.next` folder when it happens to see if it works. Though for most parts it's to do with how Shopify's package handles OAuth cookies, so if you start auth at `api.example.com` and your callback is at `dashboard.example.com`, it'll break because cookie is set to `sameSite: lax`, scoping it to that subdomain instead of the whole domain.

**Comment by ifat802** [comment]
It is happening in the production mode. 
And I am using the same subdomain on auth and the callback.

**Comment by kinngh** [comment]
Can you try this gist out?

https://gist.github.com/kinngh/ab36102f4c1f2bdd9a56729253af222b

**Comment by ifat802** [comment]
okay @kinngh

**Comment by kinngh** [comment]
@ifat802 any updates on this?

**Comment by ifat802** [comment]
The issue seems to be fixed.
The issue did not reoccur. @kinngh
