### ISSUE TITLE
Router parameters not persisting

### ISSUE THREAD

**Issue by Tom-Caz** [kinngh/shopify-nextjs-prisma-app#28]
On the initial load of my index page, I am trying to get the current store's Id using `getServerSideProps`:

```
export const getServerSideProps = async ({req}) => {
  const store_id = req.query?.host;
  {...}
}
```

This works fine on the initial render, but If I switch between tabs in the `ChannelMenu`, the parameters do not persist.

My understanding is that this code block should be persisting the parameters, but I could be wrong:

```
const history = useMemo(
    () => ({
      replace: (path) => {
        router.push(path);
      },
    }),
    [location]
  );
```

I have changed the `NavigationMenu` to a `ChannelMenu`, since that is what is required for a sales channel, but this issue still occurs even when I remove the menu.

Params on initial load:

```
{
  embedded: '1',
  hmac: '{...}',
  host: '{...}',
  locale: 'en-US',
  session: '{...}',
  shop: '{...}.myshopify.com',
  timestamp: '1688223823'
}
```
Params after selecting (or reselecting) side tab navigation:
```
{ appLoadId: '{...}' }```

I am not sure why this error is occurring. Admittedly, I am relatively new to React & NextJs, so I might just be overlooking or not fully understanding something.

Thanks!

**Comment by kinngh** [comment]
...query params are never sustained across loads, and is fundamental to how the Internet works.

Imagine you land on a page, `https://website.com/?ref=google.com`. Now when you click on a link, and assuming the website is made with the basic building blocks of the Internet, HTML and CSS, the router query params aren't passed on to `https://website.com/page?ref=google.com`. 

Now I don't understand why you'd want to sustain it, but here's two ways:

1. Fetch the query params on initial and subsequently each load, and pass it in your `router.push(path, query: {key: value})`
2. Use an external state managment library like `zustand` that, on initial load, fetches the query params and stores it client  side and you can access that state store across all your components.
