### ISSUE TITLE
How to inject custom js to shopify via app

### ISSUE THREAD

**Issue by trantrongbinh** [kinngh/shopify-nextjs-prisma-app#30]
Now I generated a js file with content. What I want is to inject this code automatically to the shopify store, so every user which installed the app the code will be added to his store autmatically.

I read about [script_tags](https://shopify.dev/docs/api/admin-rest/2023-07/resources/scripttag) but getting error: **[API] This action requires merchant approval for write_script_tags scope**
 Though I added write_script_tags to the env:
SHOPIFY_API_SCOPES=read_content,write_content,read_products,write_script_tags,read_script_tags

**Comment by kinngh** [comment]
Can you be a little more descriptive? The question does not make any sense.

**Comment by trantrongbinh** [comment]
@kinngh sorry sir, I updated question. May I do something?

**Comment by kinngh** [comment]
You're missing permissions (scopes). Add your scopes and reinstall for this to work^

**Comment by kinngh** [comment]
Script tags are being deprecated. Use a theme extension instead.

**Comment by trantrongbinh** [comment]
@kinngh But if I want is to inject this code automatically to the shopify store when every user which installed the app the code will be added to his store autmatically. If use theme extension then user need add that for theme. 
I added ```SHOPIFY_API_SCOPES=read_content,write_content,read_products,write_script_tags,read_script_tags``` and reinstalled but still got the error: ```This action requires merchant approval for write_script_tags scope```

**Comment by kinngh** [comment]
But when a user uninstalls your app or upgrades, you're stuck reinstalling and leaving code on uninstall, this is exactly why script gags are being deprecated - to stop polluting merchant's theme. 

Besides, you do realize you have a higher chance of rejection if you're using script tags, or eventually will be delisted until you migrate, right?

**Comment by trantrongbinh** [comment]
@kinngh Thank you for your prompt reply.

Any help from you if I want to do the same? I'm making an app change default search input of store shopify.

I see there are some apps that automatically add their js files to my store but just install the app you can see those js files at url: [script_tags. json](https://ttbdev.myshopify.com/admin /api/2023-07/script_tags. json)

**Comment by kinngh** [comment]
You can use a theme extension that targets the search by ID and overwrite it.
