### ISSUE TITLE
App Bridge UI Menu not corresponding to the page

### ISSUE THREAD

**Issue by AndrejMazhenkovski** [kinngh/shopify-nextjs-prisma-app#35]
Hey, building another app with this template, and I see there have been some cool updates, including transition to AppBridge CDN (#34)

If you try switching between the three different menu tabs on the lefthand side of the app, it usually does not reflect the page shown after the second switch. As you can see from the screenshot, I have the clicked the "Fetch Data" page, but the ui menu shows the "Billing" page as active. 

![image](https://github.com/kinngh/shopify-nextjs-prisma-app/assets/36366181/25cac2b4-c5d6-486e-97d0-ba3df5d9c0b1)
|

I suspect this might be completely on the AppBridge side, as I've seen some complaints on their repo that it takes longer to load a page from previous versions, but still wanted to reach out. 🙌🏽

**Comment by kinngh** [comment]
You're correct - it's a little slower and on prod mode it's still not as noticeable as on dev mode, but ye this is totally on AppBridge's end and there's nothing we can do about it except open an issue on official repos!
