### ISSUE TITLE
Unable to use Mongodb

### ISSUE THREAD

**Issue by neilpatel2292** [kinngh/shopify-nextjs-prisma-app#36]
I want to use mongodb so I modified schema.prisma file - https://prnt.sc/f0oM9YYKgsFP

when I am installing app it showing error - https://prnt.sc/wjNurYNmxeEA

I tried to solve it by making findFirst so it should redirect to -https://prnt.sc/S2sQnawsouPZ 

but it was not redirecting to new url it is giving sub frame error - https://prnt.sc/TmMM9qT0kGzl

**Comment by kinngh** [comment]
1. If you haven't used MongoDB with Prisma, or aren't comfortable with it, you should swap back to using MongoDB packages you're comfortable with
2. Your schema is wrong. MongoDB `id`s won't accept the id that is set in session aka `storename.myshopify.com_1234` format.
3. I personally won't even recommend using Prisma and MongoDB. Take a look at the implementation at the [Express x MongoDB](https://github.com/kinngh/shopify-node-express-mongodb-app) repo and migrate over that to Next.js. You can read more about using MongoDB with Next.js [here](https://www.mongodb.com/developer/languages/javascript/nextjs-with-mongodb/)

**Comment by neilpatel2292** [comment]
Got it, Thanks.
