### ISSUE TITLE
Support for App Router?

### ISSUE THREAD

**Issue by swizzmagik** [kinngh/shopify-nextjs-prisma-app#38]
Hello, do you have any plans to add this support or update this repo?

**Comment by kinngh** [comment]
- App router is still considerably slower 
- TypeScript support isn't coming, I'm a JS + JSDocs person

![IMG_3354](https://github.com/kinngh/shopify-nextjs-prisma-app/assets/773555/00b28ed5-08a7-4d32-b7bf-7f99495d77af)

**Comment by swizzmagik** [comment]
Thanks for your reply!

**Comment by swizzmagik** [comment]
I found a decent example for anyone else looking for auth flow on nextjs app router: https://github.com/ozzyonfire/shopify-next-app
