### ISSUE TITLE
The application endlessly re-authorizes

### ISSUE THREAD

**Issue by vvdimoff** [kinngh/shopify-nextjs-prisma-app#41]
The application endlessly re-authorizes when I click on the webhook or billing button in the debug menu. I tried using an older version and it works. This happens on a completely fresh install.
Dependencies of the older version wich works:
 "@prisma/client": "^5.1.1",
    "@shopify/app-bridge":"^3.7.9",
    "@shopify/app-bridge-react": "^3.7.9",
    "@shopify/polaris": "^11.11.0",
    "@shopify/shopify-api":"^7.5.1",
    "@vercel/postgres": "^0.4.1",
    "cryptr": "^6.2.0",
    "graphql": "^16.7.1",
    "next": "13.4.13",
    "next-api-middleware": "^2.0.1",
    "react": "18.2.0",
    "react-dom": "18.2.0".

**Comment by kinngh** [comment]
Just ran a fresh install on a fresh store + fresh app and an existing store and existing app and cannot replicate. Are you sure your database is writeable and there are no errors?

Also, an error log on the reauth would be great

**Comment by kinngh** [comment]
https://github.com/kinngh/shopify-nextjs-prisma-app/assets/773555/4d9ba2ed-06a0-41d7-8a3a-44fb1468df2a

**Comment by vvdimoff** [comment]
Ok, I'm trying to make fully clean installation with everything new.

**Comment by vvdimoff** [comment]
Everything works after I deleted the app completely and created it from the interface. Further a fresh installation works without problems. Thanks for your help.
