### ISSUE TITLE
Test app on development store isn't working

### ISSUE THREAD

**Issue by Devang47** [kinngh/shopify-nextjs-prisma-app#46]
when I click on test app on development store and I select a store it navigates to this URL: 

`https://tunnel.saklani.dev/?hmac=****&host=***&shop=****.myshopify.com&timestamp=***`

tunnel.saklani.dev is a cloudflare tunnel for nextjs instead of ngrok

then it redirects to 
`https://admin.shopify.com/store/palmaitest/apps/****/?hmac=****&timestamp=****`

and then it shows a 404 on the page
![Screenshot 2024-01-31 at 2 32 27 PM](https://github.com/kinngh/shopify-nextjs-prisma-app/assets/72780418/315fa8d4-5e2f-4273-a9dd-5b191160f6e6)

this installation process isn't working but when I do it like this: 
- go to https://tunnel.saklani.dev/api/auth?shop=******.myshopify.com/
it shows the installation screen and it works

I don't really know what's the issue here

**Comment by kinngh** [comment]
Clear out your `stores` and `sessions` table and try again. This is a common issue that comes with a lack of understanding of session management in the repo

**Comment by Devang47** [comment]
Okay, thanks for your help!
