### ISSUE TITLE
Proxy routes are not working using ngrok

### ISSUE THREAD

**Issue by Devang47** [kinngh/shopify-nextjs-prisma-app#47]
when I use ngrok for proxying my theme extension requests to the next proxy API routes it gives this response: 

```
You are about to visit ****.ngrok-free.app, served by ****. This website is served for free through ngrok.com. You should only visit this website if you trust whoever sent the link to you. (ERR_NGROK_6024)
``` 

but it works fine when I use a Cloudflare tunnel, maybe we should shift away from ngrok.

**Comment by kinngh** [comment]
1. When using ngrok in dev mode, you need to set bypass headers or a custom user agent
2. You're free to use any tunnel service you prefer
