### ISSUE TITLE
Potentially Missing Dependency – @shopify/polaris-icons

### ISSUE THREAD

**Issue by team-atomic** [kinngh/shopify-nextjs-prisma-app#51]
Error error thrown from ExternalMinor import on line 11 of `/pages/index.jsx`. Resolved by adding @shopify/polaris-icons as a dependency.  

<img width="552" alt="Screenshot 2024-02-24 at 3 49 51 PM" src="https://github.com/kinngh/shopify-nextjs-prisma-app/assets/59326189/ea2b9325-1d0b-4dd3-966e-0390f7f03259">

**Comment by kinngh** [comment]
Hey thank you for filing this issue - I made a mistake. It's supposed to be `ExternalIcon` and not `ExternalMinor` and you can uninstall the dependency!
