### ISSUE TITLE
Cannot install custom app to multiple stores in same Plus org

### ISSUE THREAD

**Issue by AminRafaey** [kinngh/shopify-nextjs-prisma-app#52]
I have been using an app that I created using the provided code as a starting template. It works fine for two stores but recently I tried to install an app on a new store under the same organization but this is what I am receiving. What i exactly did is after creating an app manually, setting up configurations properly and then requesting access for API scopes as needed I received a link to directly install an app on any store under the same organization.
<img width="763" alt="Screenshot 2024-03-06 at 6 17 29 PM" src="https://github.com/kinngh/shopify-nextjs-prisma-app/assets/62640101/4a4a719f-7b8a-4aa2-82df-a36b2f802ef2">

**Comment by AminRafaey** [comment]
This is what I am recieving after using this link: https://shopify-returns-app.vercel.app/api/auth?shop=[shopname].myshopify.com
If i use a link provided by Shopify from merchant link I receive shopify error page without any information. Moreover, I checked vercel logs and every request is with status code 200.

**Comment by kinngh** [comment]
- Is this a public app or a custom app
- If custom app, have you enabled install more under the same organization
- Are you on the newer version of the repo that uses Managed Install or are you using OAuth?

**Comment by AminRafaey** [comment]
Hi @kinngh thanks for the response.

- This is a custom app
- "Allow multi-store install for one Plus organization" This option is checked in my case.
- I forked this repo on "Oct 23, 2023", and I believe I am using OAuth and not on the newer version

**Comment by kinngh** [comment]
@AminRafaey Get in touch with Partner Support and see if they can sort it, because if it is installed in different stores, it means it works as expected. We've had this issue with custom apps sometimes too and getting in touch with partner support usually gets it done

**Comment by kinngh** [comment]
There was an auth outage that caused this. Closing issue.
