### ISSUE TITLE
Webhooks verification fail

### ISSUE THREAD

**Issue by ShiNxz** [kinngh/shopify-nextjs-prisma-app#56]
Seems like there is a problem with the shopify verification process
![image](https://github.com/kinngh/shopify-nextjs-prisma-app/assets/62391669/6a76f82f-e3f7-4421-929c-1a771c925c40)
Any idea what can cause the issue?

**Comment by ShiNxz** [comment]
Removing the ```export const config = {
	api: {
		bodyParser: false,
	},
}``` part from the [...webhookTopic.ts] file solved the issue.

**Comment by kinngh** [comment]
`.ts` file? There's no TypeScript in the entire repo mate

**Comment by kinngh** [comment]
I also just created a new app, pulled the repo and did basic setup and ran through the automated tests and it passed in one shot and everything is working as expected. I don't see how you managed to break the verifications, but looks like while transpiling it to TypeScript you would have overlooked something and broken down things. I do not provide support for TS but all I'm gonna say is be prepared for issues in the future mate.

<img width="601" alt="Screenshot 2024-04-16 at 11 55 33 PM" src="https://github.com/kinngh/shopify-nextjs-prisma-app/assets/773555/311c3bf0-5ada-4dbc-a654-051b36b622a2">
