### ISSUE TITLE
after billing redirecrtion won't instead show 404

### ISSUE THREAD

**Issue by jaydeepu96** [kinngh/shopify-nextjs-prisma-app#59]
I am using the latest setup, but after approving the payment from the billing section, the application redirects from the billing page to the shop page. The URL it navigates to is (https://admin.shopify.com/store/shopName/apps/appName/api/auth?charge_id=27448901798). However, this URL displays a 404 error page, and the console shows the following error message:

 GET /api/auth?charge_id=27448901798&embedded=1&hmac=a0e0b4a44a5714fa0df9a75c69dfb1c927a40027437e7855a4513bba2839013f&host=YWRtaW4uc2hvcGlmeS5jb20vc3RvcmUvYnJhZG5leHRnZW53aXNobGlzdA&id_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvYnJhZG5leHRnZW53aXNobGlzdC5teXNob3BpZnkuY29tXC9hZG1pbiIsImRlc3QiOiJodHRwczpcL1wvYnJhZG5leHRnZW53aXNobGlzdC5teXNob3BpZnkuY29tIiwiYXVkIjoiNzc0NTE3YTBmNDNkNWNiMDYzNWY1NmRhNzc1ODhkY2MiLCJzdWIiOiI4MjkwNTkyMzc1MCIsImV4cCI6MTcxNjQ3Mjc0MiwibmJmIjoxNzE2NDcyNjgyLCJpYXQiOjE3MTY0NzI2ODIsImp0aSI6Ijk3N2Y4ZWY2LWY1YmUtNDFhNC04NTUyLTc1YTlmOWEwMzY5OSIsInNpZCI6IjQ3NzQ3MDBhLWFlMTUtNDdmOC1iMzQwLTU0NDE3MGZiYTI5MiIsInNpZyI6ImY3NjhkZGYwODgzZmUzMzU2ZDEyY2EwYzRiNTQ4ZTA0M2NiZmQ0MWEzNDQzOWY2NWJmZmQxNjQ4YTA5N2I1YTYifQ.mSEcx3M8y-wQXQZZqiEEWWrOG9NqO0AOL__oBdA9j-o&locale=en-IN&session=dd7eda01a21f30b2e75aa445975d06e7add892160405f56fad58afb18c7abb6e&shop=shopName.myshopify.com&timestamp=1716472682 404 in 4837ms

**Comment by kinngh** [comment]
If you're using the latest version, you're completely wrong with your query. 

1. The route `/api/auth/*` doesn't exist anymore, it did in the previous versions
2. In your GraphQL query, define your return URL to your app's base URL and pass the shop as a param.

```
const returnUrl = `${process.env.SHOPIFY_APP_URL}/?shop=${req.user_shop}`;

  const planName = "$10.25 plan";
  const planPrice = 10.25; //Always a decimal

  const response = await client.request(
    `mutation CreateSubscription{
    appSubscriptionCreate(
      name: "${planName}"
      returnUrl: "${returnUrl}"
      test: true
      lineItems: [
        {
          plan: {
            appRecurringPricingDetails: {
              price: { amount: ${planPrice}, currencyCode: USD }
            }
          }
        }
      ]
    ) {
      userErrors {
        field
        message
      }
      confirmationUrl
      appSubscription {
        id
        status
      }
    }
  }
`
  );
```

I believe what you did was blindly copy the example and not looked into what your return URL should be.

**Comment by kinngh** [comment]
https://github.com/kinngh/shopify-nextjs-prisma-app/commit/dcef3c967f772fb27de51ba2d926a8c2f6771e57

**Comment by jaydeepu96** [comment]
I hope this message finds you well.

I wanted to take a moment to express my heartfelt gratitude for the unwavering support you've shown me. Your encouragement and belief in me have made all the difference, and I am deeply touched by your kindness.

Thank you for being a beacon of strength and inspiration. Your support has not only helped me through challenging times but has also made the successes all the more meaningful. I am truly fortunate to have you by my side.

With sincere appreciation and warmest regards,

**Comment by kinngh** [comment]
Thank you so much for the kind words!
