### ISSUE TITLE
Webhooks Not showing up

### ISSUE THREAD

**Issue by abhishek-upsellninja** [kinngh/shopify-nextjs-prisma-app#64]
1. cloned the repo 
2. added .env
3. Installed the app, asked for right scopes

![CleanShot 2024-10-13 at 16 05 04@2x](https://github.com/user-attachments/assets/e37b1034-17dc-4f55-b96e-e77e1329158e)

![CleanShot 2024-10-13 at 16 06 04](https://github.com/user-attachments/assets/76e5003f-04a5-45cd-a569-32a98e14f1c2)

Not even the Uninstall Webhook shows up

Active webhook returns 200

![CleanShot 2024-10-13 at 16 07 44](https://github.com/user-attachments/assets/c3aef068-2f2c-4967-99e1-d5a4c01b69dd)

but "webhookSubscriptions" are coming empty

![CleanShot 2024-10-13 at 16 08 25](https://github.com/user-attachments/assets/be28e5e8-d7f6-405a-a1cf-3c9a2199fd67)

**Comment by kinngh** [comment]
Webhooks registered with TOML don't show up with this specific GraphQL query and is a known thing. This was still left in place so migrations from GraphQL to TOML based webhooks are straight forward.

There's currently no known GraphQL query that pulls webhooks registered via TOML.
