### ISSUE TITLE
Oauth error failed_grant_with_invalid_scopes: The application could not be installed due to invalid scopes requested.

### ISSUE THREAD

**Issue by berktaylan** [kinngh/shopify-nextjs-prisma-app#65]
![image](https://github.com/user-attachments/assets/83dd174a-fac8-4d89-bb0b-a4423340201b)

```SHOPIFY_API_SCOPES=read_products,write_products```

And when i check the localhost:3000

I see

![image](https://github.com/user-attachments/assets/4fc01a43-0672-4cdd-84af-65d22045bc84)

Its fresh install

Only change i made , changing prisma to use mongodb

```
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

model stores {
  shop     String   @id @map("_id")
  isActive Boolean? @default(false)

  // Removed @@index([shop]) as it’s not needed for the _id field
}

model session {
  id      String  @id @map("_id")
  content String?
  shop    String?

  // Index only for `shop`, no need for explicit `id` index
  @@index([shop])
}

```

**Comment by berktaylan** [comment]
I forgot to run `npm run update:config`

Closing it.

**Comment by kinngh** [comment]
Just a heads up - this isn't going to run on `localhost:3000` since Shopify requires a HTTPS connection between the platform and the app. You're gonna have to use tunneling program like Cloudflare Tunnels, Ngrok or alternatives to build apps.
